spring.application.name=boot.amazon-products
server.port=8080

#spring.data.mongodb.uri=mongodb+srv://ankitkjha18_db_user:uEikVFRRQpmr7ovD@mycluster1.xxxx.mongodb.net/ProductsDB?retryWrites=true&w=majority
#spring.mongodb.uri=mongodb+srv://ankitkjha18_db_user:uEikVFRRQpmr7ovD@mycluster1.rbiiean.mongodb.net/ProductsDB?retryWrites=true&w=majority

#spring.data.mongodb.uri=mongodb+srv://ankitkjha18_db_user:uEikVFRRQpmr7ovD@mycluster1.rbiiean.mongodb.net/?appName=MyCluster1
spring.mongodb.uri=mongodb+srv://ankitkjha18_db_user:uEikVFRRQpmr7ovD@mycluster1.rbiiean.mongodb.net/?appName=MyCluster1

spring.mongodb.database=ProductsDB